ShopVongTay/Models/KhachHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopVongTay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public int MaKH { get; set; }
        public string HoTenKH { get; set; }
        public string DiaChiKH { get; set; }
        public string SoDienThoaiKH { get; set; }
        public string TenDN { get; set; }
        public string MatKhau { get; set; }
        public Nullable<System.DateTime> NgaySinhKH { get; set; }
        public string GioiTinh { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
    }
}

ShopVongTay/Areas/Admin/Controllers/QLKhachHangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopVongTay.Models;
using System.ComponentModel;
using System.Linq.Dynamic;
using System.Linq.Expressions;
using System.Reflection;
using PagedList;
using System.Data.Entity;
using System.Threading;
using System.Globalization;

namespace ShopVongTay.Areas.Admin.Controllers
{
    public class QLKhachHangController : Controller
    {
        ShopVongTayEntities db = new ShopVongTayEntities();
        // GET: Admin/QLKhachHang
        public class HttpParamActionAttribute : ActionNameSelectorAttribute
        {
            public override bool IsValidName(ControllerContext controllerContext, string actionName, MethodInfo methodInfo)
            {
                if (actionName.Equals(methodInfo.Name, StringComparison.InvariantCultureIgnoreCase))
                    return true;

                var request = controllerContext.RequestContext.HttpContext.Request;
                return request[methodInfo.Name] != null;
            }
        }
        public ActionResult KhachHang()
        {
            return View();
        }
        [HttpGet]
        public ActionResult KhachHang(int? size, int? page, string sortProperty, string sortOrder, string searchString)
        {
            if (Session["MaAD"] == null)
            {
                return RedirectToAction("DangNhapAdmin", "DangNhapAdmin");
            }

            ViewBag.searchValue = searchString;
            ViewBag.sortProperty = sortProperty;
            ViewBag.page = page;

            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "5", Value = "5" });
            items.Add(new SelectListItem { Text = "10", Value = "10" });
            items.Add(new SelectListItem { Text = "20", Value = "20" });
            items.Add(new SelectListItem { Text = "25", Value = "25" });

            foreach (var item in items)
            {
                if (item.Value == size.ToString()) item.Selected = true;
            }
            ViewBag.size = items;
            ViewBag.currentSize = size;

            var links = from l in db.KhachHangs select l;
            // 5. T?o thu?c tính s?p x?p m?c d?nh là "LinkID"
            if (String.IsNullOrEmpty(sortProperty)) sortProperty = "BookId";

            // 5. S?p x?p tang/gi?m b?ng phuong th?c OrderBy s? d?ng trong thu vi?n Dynamic LINQ
            if (sortOrder == "desc") links = links.OrderBy(sortProperty + " desc");
            else if (sortOrder == "asc") links = links.OrderBy(sortProperty);
            else links = links.OrderBy("HoTenKH");

            if (!String.IsNullOrEmpty(searchString))
            {
                links = links.Where(s => s.HoTenKH.Contains(searchString));
            }

            page = page ?? 1;


            int pageSize = (size ?? 5);

            ViewBag.pageSize = pageSize;

            // 6. Toán t? ?? trong C# mô t? n?u page khác null thì l?y giá tr? page, còn
            // n?u page = null thì l?y giá tr? 1 cho bi?n pageNumber. --- dammio.com
            int pageNumber = (page ?? 1);

            // 6.2 L?y t?ng s? record chia cho kích thu?c d? bi?t bao nhiêu trang
            int checkTotal = (int)(links.ToList().Count / pageSize) + 1;
            // N?u trang vu?t qua t?ng s? trang thì thi?t l?p là 1 ho?c t?ng s? trang
            if (pageNumber > checkTotal) pageNumber = checkTotal;

            return View(links.ToPagedList(pageNumber, pageSize));

        }
        [HttpPost, HttpParamAction]
        public ActionResult Reset()
        {
            ViewBag.searchValue = "";
            //IndexAdmin(null, null, "", "", "");
            return View();

        }
        public ActionResult Edit(int? id)
        {
            //Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(language);
            //Thread.CurrentThread.CurrentUICulture = new CultureInfo(language);

            //ViewBag.imgurl = db.SanPhams.SingleOrDefault(n => n.MaSP == id).HinhAnh;
            // List<Category> lis = db.Categories.ToList();

            KhachHang sp = db.KhachHangs.Find(id);
            return View(sp);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaKH,HoTenKH,DiaChiKH,SoDienThoaiKH,TenDN,MatKhau,NgaySinhKH,GioiTinh,Email")]  KhachHang sp)
        {
            if (ModelState.IsValid)
            {
                sp.NgaySinhKH = DateTime.Now;
                db.Entry(sp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("KhachHang");
            }
            return View(sp);
        }
        public ActionResult Delete(int? id)
        {

            KhachHang sp = db.KhachHangs.Find(id);
            Session["itemid"] = id;
            return View(sp);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            KhachHang sp = db.KhachHangs.Find(id);
            db.KhachHangs.Remove(sp);
            db.SaveChanges();
            return RedirectToAction("KhachHang");
        }
    }
}

ShopVongTay/Areas/Admin/Views/QLKhachHang/Delete.cshtml
@model ShopVongTay.Models.KhachHang
@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<style>
    .frmauthor {
        font-family: serif;
    }

    .btncreate {
        background-color: #e7ab3c;
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        color: white;
    }

    table {
        text-align: center;
    }

    th {
        color: white;
        background-color: #e7ab3c;
    }
</style>
@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()
    <div class="w3-container w3-brown">
        <h2>Xóa Thông Tin Khách Hàng</h2>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Họ Tên</th>
                <th>Địa Chỉ</th>
                <th>Số Điện Thoại</th>
                <th>Tên ĐN</th>
                <th>Mật Khẩu</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.HoTenKH)
                </td>
                <td>  @Html.DisplayFor(model => model.DiaChiKH)</td>

                <td>
                    @Html.DisplayFor(model => model.SoDienThoaiKH)
                </td>
                <td>@Html.DisplayFor(model => model.TenDN)</td>
                <td>
                    @Html.DisplayFor(model => model.MatKhau)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Email)
                </td>
            </tr>
        </tbody>
    </table>
    <script>
        function xoa() {
            alert("Xóa thành công!");
        }
    </script>

    <a href="@Url.Action("KhachHang","QLKhachHang")" class="btncreate">Quay Lại</a>

    <input type="submit" onclick="xoa()" class="btncreate" style="width:130px; background-color:#e7ab3c" value="Xóa" />

}

ShopVongTay/Areas/Admin/Views/QLKhachHang/Edit.cshtml
@model ShopVongTay.Models.KhachHang
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<link href="~/css/editkhachhang.css" rel="stylesheet" />
@using (Html.BeginForm())
{
    <div class="content-edit" style="margin-left:100px;">

        @Html.AntiForgeryToken()
        <h4 style="font-family:serif; margin-left:-48px">Sửa Thông Tin Khách Hàng</h4>
     
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaKH)


        @*@Html.EditorFor(model => model.MaKH, new { htmlAttributes = new { @class = "form-control", @style = "display: none" } })
        @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })*@

        @Html.EditorFor(model => model.MaKH, new { htmlAttributes = new { @class = "form-control", @style = "display: none" } })
        @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })

        <div class="right">
            <label class="control-label">Tên Khách Hàng </label>   @Html.EditorFor(model => model.HoTenKH, new { htmlAttributes = new { @class = "form-control" } })

            @Html.ValidationMessageFor(model => model.HoTenKH, "", new { @class = "text-danger" })
            <label class="control-label">Địa Chỉ</label>
            @Html.EditorFor(model => model.DiaChiKH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChiKH, "", new { @class = "text-danger" })
            <label class="control-label">Số ĐT</label>
            @Html.EditorFor(model => model.SoDienThoaiKH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoDienThoaiKH, "", new { @class = "text-danger" })
            <label class="control-label">Tên ĐN</label>
            @Html.EditorFor(model => model.TenDN, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="left">
            @*<label class="control-label">Trạng Thái</label>
            <select class="dropdown editdropdown" name="trangthai">
                <option value="@Model.TrangThai">@Model.TrangThai</option>
                <option value="Đã giao">Đã giao</option>
                <option value="Đang giao">Đang giao</option>
            </select>*@
            <label class="control-label">Mật Khẩu</label>
            @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            <label class="control-label">Email</label>
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            <a href="@Url.Action("KhachHang","QLKhachHang")" style="margin-left:-55px; margin-top:22px;" class="btncreate">Quay Lại</a>

            <input type="submit" class="btncreate" style="width:130px; background-color:#e7ab3c" value="Lưu" />
        </div>

    </div>

}

ShopVongTay/Areas/Admin/Views/QLKhachHang/KhachHang.cshtml
@using ShopVongTay.Models
@model PagedList.IPagedList<ShopVongTay.Models.KhachHang>
@using PagedList.Mvc


@{
    ViewBag.Title = "KhachHang";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<link href="~/css/CSSAD.css" rel="stylesheet" />
<style>
    .frmauthor {
        font-family: serif;
    }

    .btncreate {
        background-color: red;
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        color: white;
    }

    table {
        text-align: center;
    }

    th {
        color: white;
        background-color: #17aa67;
    }
</style>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
@*<p>Danh Sách Sản Phẩm</p>
    <hr />*@
<body>
    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">

                <div class="row" style="padding-top:10px">
                    <div class="col-sm-4">

                        <div class="show-entries">
                            @using (Html.BeginForm("KhachHang", "QLKhachHang", FormMethod.Get))
                            {
                                <p>
                                    Hiển thị @Html.DropDownList("size", (List<SelectListItem>)ViewBag.size, new { @onchange = "this.form.submit();" })
                                    @Html.Hidden("page", (object)ViewBag.page)
                                    @Html.Hidden("sortProperty", (object)ViewBag.sortProperty)
                                    @Html.Hidden("sortOrder", (object)ViewBag.sortOrder)
                                    @Html.Hidden("searchString", (object)ViewBag.searchValue)
                                </p>
                                @*<a class="themsach" href="@Url.Action("CreateSP","AdminCRUD")">Thêm Sản Phẩm</a>*@
                            }
                        </div>

                    </div>


                    <div class="search-box">
                        @*<div class="input-group">

                                @using (Html.BeginForm("Index", "AdminCRUD", FormMethod.Get))
                                {

                                    @Html.TextBox("searchString", (string)ViewBag.searchValue, new { @class = "form-control", @placeholder = "Search" }) <input type="submit" value="Tìm kiếm" />
                                }

                            </div>*@

                        @*<form action="/Admin/AdminCRUD/Index" method="get" class="formsearch">
                                <span class="input-group-addon"><i class="material-icons">&#xE8B6;</i></span>
                                <input class="" id="searchString" name="searchString" placeholder="Search" type="search">
                            </form>*@

                    </div>

                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Mã </th>
                        <th>Tên</th>

                        <th>Địa Chỉ</th>
                        <th>
                            Số ĐT
                            <i></i>
                        </th>
                        <th>
                            Tên ĐN
                        </th>
                        <th>
                            Mật Khẩu
                        </th>
                        <th>
                            Giới Tính
                        </th>
                        <th>
                            Email
                        </th>
                        <th>
                            Xử Lí
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>

                        <td>@item.MaKH</td>
                        <td>@item.HoTenKH</td>

                        <td>
                            @item.DiaChiKH
                        </td>
                        <td>@item.SoDienThoaiKH</td>
                        <td>@item.TenDN</td>
                        <td>@item.MatKhau</td>
                        <td>@item.GioiTinh</td>
                        <td>@item.Email</td>
                        <td>
                            <button type="button" rel="tooltip" class="btn btn-info btn-round btn-just-icon btn-sm" data-original-title="" title="">
                                <a href="@Url.Action("Edit", "QLKhachHang", new { id = item.MaKH })">
                                    <i class="material-icons">edit</i>
                                </a>
                            </button>


                            <button type="button" rel="tooltip" class="btn btn-danger btn-round btn-just-icon btn-sm" data-original-title="" title="">
                                <a href="@Url.Action("Delete", "QLKhachHang", new { id = item.MaKH })">
                                    <i class="material-icons">
                                        close
                                    </i>
                                </a>
                            </button>
                        </td>
                    </tr>
                    }



                </tbody>
            </table>
            <div class="clearfix">
                <div class="hint-text">Showing @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) out of @Model.PageCount entries</div>
                <ul class="pagination">

                    <li class="page-item">@Html.PagedListPager(Model, page => Url.Action("KhachHang", new { page, size = ViewBag.currentSize }))</li>

                </ul>
            </div>
        </div>
    </div>
</body>